name: digitalminaret
description: "Sunucusuz, offline namaz vakitleri uygulamasi."
publish_to: 'none'
version: 1.0.4+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core functionality
  adhan: ^2.0.0
  geolocator: ^14.0.2
  geocoding: ^3.0.0

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Audio
  just_audio: ^0.9.36
  audio_session: ^0.1.25
  path_provider: ^2.1.5

  # Widget
  home_widget: ^0.9.0

  # Background tasks
  workmanager: ^0.9.0+3

  # UI/UX
  intl: ^0.20.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_qiblah: ^3.2.0
  permission_handler: ^11.3.0
  url_launcher: ^6.3.1
  purchases_flutter: ^8.10.1
  flutter_islamic_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  clock: ^1.1.1
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
